### ISSUE TITLE
Offline instrumentation required to enable coverage of runtime transformed classes (e.g. Powermock)

### ISSUE THREAD

**Issue by mchr3k** [mchr3k/jacoco#2]

**Comment by mchr3k** [comment]
I need to modify the agent to startup the same runtime as was used by the instrumenttask.

**Comment by mchr3k** [comment]
See: 4909eb192b53fe831063114e68db198f8a8cb514

**Comment by mchr3k** [comment]
This now works but needs tests.

**Comment by marchof** [comment]
I had a quick look at the change set: Note that a important use case for offline instrumentation are environments where no Java agent is available (e.g. Android VM).

**Comment by mchr3k** [comment]
Good point. Do you have any suggestions for how to initialise the runtime without an agent? 

I wonder if a new runtime could be used which would insert explicit calls to a JaCoCo class. A static initializer on the JaCoCo class coud initialize the runtime.

**Comment by marchof** [comment]
Yes, this is the only way I currently see: A direct dependency from instrumented classes to the JaCoCo runtime.

**Comment by marchof** [comment]
@mchr3k 

Here is a implementation for offline mode: https://github.com/jacoco/jacoco/pull/58

**Comment by mchr3k** [comment]
Thanks for the reference. My fork already has offline instrumentation - is your implementation similar? I'll check myself later but I'm on my phone just now.

Also, merry Xmas :)
